model = "Qwen/Qwen3-4B-Instruct-2507"

[env]
id = "math-group"

[env.args]
advantage_mode = "gdpo"

[inference]
gpus = 1

[inference.args]
enforce_eager = true
gpu_memory_utilization = 0.9

[trainer]
gpus = 1
run_name = "gdpo-math-group"

[trainer.args]
micro_batch_size = 8
rollouts_per_example = 16
batch_size = 256
max_steps = 200
max_seq_len = 4096
max_tokens = 2048
learning_rate = 1e-5
