[[env]]
env_id = "gsm8k"
num_examples = 20
rollouts_per_example = 1
sampling_args = { max_tokens = 1024 }
independent_scoring = true
save_results = true
save_every = 10

[[env]]
env_id = "alphabet-sort"