[env]
env_id = "math-python"
num_examples = 5
rollouts_per_example = 1

[[eval]]
[eval.model]
model = "openai/gpt-5-nano"

[[eval]]
[eval.model]
model = "openai/gpt-5-mini"

[[eval]]
[eval.model]
model = "openai/gpt-5"
